# Generated by Django 3.1.4 on 2020-12-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='pizza_type',
            field=models.CharField(choices=[('Square', 'square'), ('Regular', 'regular')], max_length=150),
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='topping_type',
        ),
        migrations.AddField(
            model_name='pizza',
            name='topping_type',
            field=models.ManyToManyField(to='pizza.Toppings'),
        ),
    ]
