"""
Django settings for ecommerce project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '3kv302m8b53wwd*0f+-gk4nozpc!co50(!ks9-a!i+7m7h5-ql'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'social_django',


    # our apps
    'core',
    'accounts',
    'addresses',
    'analytics',
    'products',
    'search',
    'tags',
    'carts',
    'orders',
    'billing',
    'marketing',
    'category',


]


FORCE_SESSION_TO_ONE = False
FORCE_INACTIVE_USER_ENDSESSION = False

MAILCHIMP_API_KEY = "ce19ae476a4d1ad540b88ab4ce5a116c-us19"
MAILCHIMP_DATA_CENTER = "us19"
MAILCHIMP_EMAIL_LIST_ID = "a585924ae3"


STRIPE_SECRET_KEY="sk_test_51HTjAFHGcIEXy6MZxvpNEUHviHVMMzR3o3MDrfQTQBEfMxu8dUkd6rXjqEgh7MaVgAFtM2iu2Dx8WFOl2qRYHOvk009J3t2eCu"
STRIPE_PUB_KEY = "pk_test_51HTjAFHGcIEXy6MZq7tC7yVKQPoTfEgr4wStVSfyYo7MvppcEPyHCRNlPZevZoFjJUJGdbfhjY96Hx0HOJrhNqDA00OAjJoE5H"

AUTH_USER_MODEL = 'accounts.User'   # changes the built-in user model to ours

LOGIN_URL='/login'
LOGIN_URL_REDIRECT='/'
LOGOUT_URL='/logout/'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
]

LOGOUT_REDIRECT_URL ='/login/'

ROOT_URLCONF = 'ecommerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecommerce.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

AUTHENTICATION_BACKENDS = (
    'social_core.backends.github.GithubOAuth2',
    'social_core.backends.twitter.TwitterOAuth',
    'social_core.backends.facebook.FacebookOAuth2',

    'django.contrib.auth.backends.ModelBackend',
)


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'
# TIME_ZONE = 'Asia/Kolkata'
# TIME_ZONE = 'America/Toronto'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS =[
    os.path.join(BASE_DIR,"static_my_proj"),

]

STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR),"static_cdn","static_root")


MEDIA_URL='/media/'

MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR),"static_cdn","media_root")
PROTECTED_ROOT = os.path.join(os.path.dirname(BASE_DIR),"static_cdn","protected_media")



EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'newakashverma25274@gmail.com'
EMAIL_HOST_PASSWORD = 'lxbjpmxfpdtmiuzy'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'Akash Team <akash@website.com>'

BASE_URL = '127.0.0.1:8000'

MANAGERS = (
    ("Akash Verma","akash@gmail.com")
)
ADMINS = MANAGERS


SOCIAL_AUTH_GITHUB_KEY = 'd1bb39be0aef5b9bda1a' #config('SOCIAL_AUTH_GITHUB_KEY')
SOCIAL_AUTH_GITHUB_SECRET = 'dbb79e72999f448acdb9a80574d7295e9acc2a21' #config('SOCIAL_AUTH_GITHUB_SECRET')

SOCIAL_AUTH_TWITTER_KEY = 'MSpwcMpxyzzVzaAnqTUz4SWR5'
SOCIAL_AUTH_TWITTER_SECRET = 'S8w3Vuf3dpa3ubTFVRjACEXacNurwilX6QtSiVGExyXA6PtuCh'

SOCIAL_AUTH_FACEBOOK_KEY = '976666946161329'
SOCIAL_AUTH_FACEBOOK_SECRET = 'dd88a35e4e472e18379e9c41a0405867'

SOCIAL_AUTH_LOGIN_ERROR_URL = '/settings/'
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/settings/'
SOCIAL_AUTH_RAISE_EXCEPTIONS = False




