"""
Django settings for BlogProject project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'oy+u+y(h-izl-6zrzk6ne_a)=llh+jz0$toli6us09tlgg+4l5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # third party apps
    'crispy_forms',
    'pagedown',
    'markdown_deux',
    'rest_framework',
    'social_django',
    'django.contrib.sites',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.github',
    'allauth.socialaccount.providers.linkedin',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.twitter',

    # local apps
    'posts',
    'comments',
    'accounts',

]

SITE_ID = 1

CRISPY_TEMPLATE_PACK = 'bootstrap3'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
]

ROOT_URLCONF = 'BlogProject.urls'
LOGIN_URL = '/login/'
LOGOUT_URL='/logout/'
LOGIN_REDIRECT_URL='home'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',  # <-- Here
                'social_django.context_processors.login_redirect',  # <-- Here
            ],
        },
    },
]


AUTHENTICATION_BACKENDS = (
    'social_core.backends.facebook.FacebookOAuth2',
    'social_core.backends.twitter.TwitterOAuth',
    'social_core.backends.github.GithubOAuth2',

    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
)


WSGI_APPLICATION = 'BlogProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS =[
        os.path.join(BASE_DIR,'staticfiles')
]

STATIC_ROOT = os.path.join(BASE_DIR,'cdn_test','static')

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR,'cdn_test', "media")



from pathlib import Path

if DEBUG:
    Path(STATIC_ROOT).mkdir(parents=True, exist_ok=True)
    Path(MEDIA_ROOT).mkdir(parents=True, exist_ok=True)



REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',

    ],
    # 'DEFAULT_PARSER_CLASSES': [
    #     'rest_framework.parsers.JSONParser',
    # ]

    'DEFAULT_AUTHENTICATION_CLASSES':[
                        # 'rest_framework.authentication.SessionAuthentication',
                        # 'rest_framework.authentication.BasicAuthentication'
                        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',

    ],
    "DEFAULT_PERMISSION_CLASSES":[
        # 'rest_framework.permissions.AllowAny',
        # 'rest_framework.permissions.IsAuthenticatedOrReadOnly',
        'rest_framework.permissions.IsAuthenticated',
                    ]
}


SOCIAL_AUTH_FACEBOOK_KEY = '364952134782794'  # App ID
SOCIAL_AUTH_FACEBOOK_SECRET = '69a2f8f505804cc58fe640ecc3615f17'  # App Secret
#
SOCIAL_AUTH_TWITTER_KEY = 'oB0jDXkvLKDSoVEeqBeS7i3ip'  # App ID
SOCIAL_AUTH_TWITTER_SECRET = '7agcTqABT2C0pE0knioFuqVEEJ2B0xLUCDD8sLSivOrb6iNCau'  # App Secret
#
#
SOCIAL_AUTH_GITHUB_KEY = '81e8a4ae283535e7b162'  # App ID
SOCIAL_AUTH_GITHUB_SECRET = '8f3ceded8e234013e2d688375575eaddf1e6547e'  # App Secret